{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.credentials",
    "module": "credentials",
    "version": "1.2.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.2.0-rc01"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.2.0-rc01.aar",
          "url": "credentials-1.2.0-rc01.aar",
          "size": 452349,
          "sha512": "de53e15fbab64cf4e448f6848a30d662af7760487ed2f95a51d409705ea3e8c43aa765398dc8c642e63c2d591c1db22ebb0284ea44fbbf717bdaa59225f275a9",
          "sha256": "498f651b4f9166bf770f6ca97aeba8e921eec101b3dff8d9f0c51ac8f6e402a4",
          "sha1": "1afb175ff53b796445ac4c3686f4e1088bbf6dd7",
          "md5": "edbe47a03e63b0102ab18f7e1c894f62"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.2.0-rc01"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.2.0-rc01.aar",
          "url": "credentials-1.2.0-rc01.aar",
          "size": 452349,
          "sha512": "de53e15fbab64cf4e448f6848a30d662af7760487ed2f95a51d409705ea3e8c43aa765398dc8c642e63c2d591c1db22ebb0284ea44fbbf717bdaa59225f275a9",
          "sha256": "498f651b4f9166bf770f6ca97aeba8e921eec101b3dff8d9f0c51ac8f6e402a4",
          "sha1": "1afb175ff53b796445ac4c3686f4e1088bbf6dd7",
          "md5": "edbe47a03e63b0102ab18f7e1c894f62"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.2.0-rc01"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.2.0-rc01-sources.jar",
          "url": "credentials-1.2.0-rc01-sources.jar",
          "size": 182945,
          "sha512": "9d1097d8f2d3aca9491b6e6efa564f79edb555c6e848de9279053b690e8c9f8f16622b687c362ea8be8f53effc5dfe5099c32f2ed586cfac37ec77f1ce9a838f",
          "sha256": "edec2215fa300cead466281b5137b4de9c6315ad9f4bae67294ccfcabeb46c0c",
          "sha1": "66a16a821867df67d0573ad3dd58c9d4b63e2e57",
          "md5": "440468b9b54804c33df8d8e5def559fc"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.2.0-rc01"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.2.0-rc01-versionMetadata.json",
          "url": "credentials-1.2.0-rc01-versionMetadata.json",
          "size": 51578,
          "sha512": "61cfa5dd0f09dcb69907f759342eafa271c2cdcc6297aa60059d5b7bf932546b057b78c41f5f3b757ef944859f4f09a713a3cadcae251a490fef2072fbcaa570",
          "sha256": "51f52587ccc388fdd77380b5ed3015eb5e1a8f326f4b07b3d5372dc9fb073408",
          "sha1": "cc3a59fbc4b59b6d49d31fe08c54633dab8f0e69",
          "md5": "e75b0f9dadd3831bbbe88d209878a008"
        }
      ]
    }
  ]
}